<a href="https://colab.research.google.com/github/Sanaullahbaig/numpy-tutorial-notebook/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Array**

In [2]:
import numpy as np

l = [1, 2, 3, 4]
a = np.array(l)

print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


Check time for execution

In [ ]:
%timeit l = [1, 2, 3, 4]

%timeit a = np.array([1, 2, 3, 4])

# %%timeit for whole program

58.1 ns ± 0.968 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
960 ns ± 284 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


One dimension array


In [ ]:
ar1 = np.array([1, 2, 3, 4])
print(ar1)
# for type
print(type(ar1))
# for dimension
print(ar1.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


Two dimension array

In [ ]:
# you must have to give the same lenght of all lines
ar2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


Three dimension array

In [ ]:
ar3 = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 1, 2, 3]]])

print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [5 6 7 8]
  [9 1 2 3]]]
3


Multi dimension array

In [ ]:
# Here it is 10 dimension array
arn = np.array([1, 2, 3, 4], ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


Zeros array using function zeros


In [ ]:
# 1 dimension array with 4 values all values will be zero
zero1 = np.zeros(4)
# 2 dimensions array with 3 rows and 4 columns values all values will be zero
zero2 = np.zeros((3, 4))
# 3 dimension array
zero3 = np.zeros(((4, 2)))

print(zero1)
print(zero2)
print(zero3)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


Ones array using function ones

In [ ]:
# 1 dimension array with 4 values all values will be one
zero1 = np.ones(4)
# 2 dimensions array with 3 rows and 4 columns values all values will be one
zero2 = np.ones((3, 4))
# 3 dimension array
zero3 = np.ones(((4, 2)))

print(zero1)
print(zero2)
print(zero3)

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


Empty array


In [ ]:
a = np.empty(4)

print(a)

[1. 1. 1. 1.]


Array with range using function arange

In [ ]:
a = np.arange(8)

print(a)

[0 1 2 3 4 5 6 7]


Diagonal element using function eye

In [ ]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a = np.eye(3,5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


Array with space using function linspace

In [ ]:
a = np.linspace(0, 20, num = 5)
print(a)

[ 0.  5. 10. 15. 20.]


Creating array with random number

rand() generating values between 0 and 1

In [ ]:
a = np.random.rand(4)

print(a)

# 2 dimension array
b = np.random.rand(2, 5)
print(b)

[0.22190556 0.00816437 0.13545489 0.63533631]
[[0.45003789 0.57481789 0.79530157 0.67030901 0.86575782]
 [0.00733564 0.62992146 0.16557851 0.93821122 0.55101184]]


randn() generating numbers close to zero, negative and positive

In [ ]:
a = np.random.randn(5)
print(a)

b= np.random.randn(2,5)
print(b)

[-0.41945391 -0.46787303 -0.74795124 -0.30753407  0.33774192]
[[-0.49385418  0.19970572 -0.20223392 -0.05452197  0.58491328]
 [-0.62866933  0.33663399  0.80880972 -0.99750032 -0.75620847]]


ranf() range is from 0 to 1 0 is included but 1 is not

In [ ]:
a = np.random.ranf(5)
print(a)

[0.43136449 0.1419944  0.59379887 0.9860092  0.30448957]


randint() generate number between two numbers

In [ ]:
#                 (min, max, total_values)
a = np.random.randint(2, 6, 3)

print(a)

[4 2 3]


Data Type

In [ ]:
a = np.array([1, 2, 3, 4, 1988293, -9999283767281237])
print(f"Data type of a is :", a.dtype)

b= np.array([0.9283746, 0.82367, 0.823743 ,0.9238])
print(f"Data type of b is: ", b.dtype)

c = np.array(["A", "B", "C", "D"])
print(f"Data type of c is: ", c.dtype)

d = np.array(["A", "B", "C", "D", 1, 2, 0.4563])
print(f"Data type of d is: ", d.dtype)

Data type of a is : int64
Data type of b is:  float64
Data type of c is:  <U1
Data type of d is:  <U32


Converting datatype of array

In [ ]:
a = np.array([1, 2, 3, 4], dtype = np.int8)
print(f"Data type of a is:", a.dtype)

Data type of a is: int64


Arthemetic Opertions in Numpy array

In [ ]:
# Adding array with single number
a = np.array([1, 2, 3, 4])
b = a + 3
print(b)


[4 5 6 7]


Adding two array


In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([9, 8, 7, 6])
c = a + b
print(c)


# Operator
add = np.add(a, b)
subtract = np.subtract(a, b)
multiply = np.multiply(a, b)
divide = np.divide(a, b)
mod = np.mod(a, b)
power = np.power(a, b) # first number second power
reciprocal_a = np.reciprocal(a) # 1/a
reciprocal_b = np.reciprocal(b) # 1/b


print(add)
print(subtract)
print(multiply)
print(divide)
print(mod)
print(power)
print(reciprocal_a)
print(reciprocal_b)

[10 10 10 10]
[10 10 10 10]
[-8 -6 -4 -2]
[ 9 16 21 24]
[0.11111111 0.25       0.42857143 0.66666667]
[1 2 3 4]
[   1  256 2187 4096]
[1 0 0 0]
[0 0 0 0]


2D Array


In [ ]:
a = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
b = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])

add = np.add(a,b)
print(add)

# Same like 1 dimension array

[[2 4 6 8]
 [2 4 6 8]]


Arthemetic Functions

In [ ]:
a = np.array([1, 2, 9, 4, 5])
print(a)
# for maximum value
print(np.max(a))
# for minimum value
print(np.min(a))
# for index of minimum value
print(np.argmin(a))
# for index of minimum value
print(np.argmax(a))
# for squareroot
print(np.sqrt(a))
# for sin value
print(np.sin(a))
# for cos value
print(np.cos(a))
# comunity sum, it will sum all the first value
print(np.cumsum(a))


[1 2 9 4 5]
9
1
0
2
[1.         1.41421356 3.         2.         2.23606798]
[ 0.84147098  0.90929743  0.41211849 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.91113026 -0.65364362  0.28366219]
[ 1  3 12 16 21]


In 2D array

In [ ]:
# Two axis o for column and 1 for row
a = np.array([[1, 2, 3], [5, 4, 8]])
# it will check the maximun value in row
maximun = np.max(a, axis = 1)
print(maximun)

[3 8]


Shape and Reshaping in Numpy arrays

Shape

In [ ]:
a = np.array([[1, 3, 5, 6],[3, 5, 8, 9]])

print(a)
print(f"Shape of a is: {a.shape}")

[[1 3 5 6]
 [3 5 8 9]]
Shape of a is: (2, 4)


Giving multiple dimension

In [ ]:
a = np.array([1, 2, 3, 4], ndmin = 5)
print(a)
print(a.ndim)
print(a.shape)

[[[[[1 2 3 4]]]]]
5
(1, 1, 1, 1, 4)


Reshaping

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
print(a.ndim)

x = a.reshape(3,2)
print(x)
print(x.ndim)


[1 2 3 4 5 6]
1
[[1 2]
 [3 4]
 [5 6]]
2


Reshaping in 3D array

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(a)
print(f"Dimension of a is: {a.ndim}")

b = a.reshape(2, 3, 2)
print(b)
print(f"Dimension of b is: {b.ndim}")

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape of a is: (12,)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Shape of b is: (2, 3, 2)


Reshaping to 1D array

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(a)
print(f"Dimension of a is: {a.ndim}")

b = a.reshape(2, 3, 2)
print(b)
print(f"Dimension of b is: {b.ndim}")

one = b.reshape(-1)
print(one)
print(f"Dimension of b is: {one.ndim}")

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Dimension of a is: 1
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Dimension of b is: 3
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Dimension of b is: 1


Broadcast Error

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3])

print(a + b)




ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [ ]:
a = np.array([1, 2, 3])
print(a)
print(a.shape)
print(a.ndim)
print()
b = np.array([[1], [2], [3]])
print(b)
print(b.shape)
print(b.ndim)
print()

c = (a + b)
print(c)
print(c.shape)
print(c.ndim)

[1 2 3]
(3,)
1

[[1]
 [2]
 [3]]
(3, 1)
2

[[2 3 4]
 [3 4 5]
 [4 5 6]]
(3, 3)
2


In [ ]:
x = np.array([[1],[2]])
y = np.array([[1, 2, 3], [1, 4, 3]])

z = (x + y)
print(z)

[[2 3 4]
 [3 6 5]]


Indexing

In [8]:
# 1D array
a = np.array([1, 2, 3, 4])
print(a[2])
print(a[-3])

# 2D array
b = np.array([[1, 2, 3], [1, 2, 3]])
print(b[0, 1])

# 3D array
c = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(c[0, 1, 1])

3
2
2
5


Slicing

In [13]:
# 1D array
a = np.array([1, 2, 3, 4, 5, 6, 7])
 #     index: 0, 1, 2, 3, 4, 5, 6
print(a[1:5])
print(a[:6])
print(a[0:])
# it will print from start to end and will jump by one element
print(a[::2])
print(a[0:7:2])

# 2D array
# for 2D array give it's index number as given in the above program

[2 3 4 5]
[1 2 3 4 5 6]
[1 2 3 4 5 6 7]
[1 3 5 7]
[1 3 5 7]


Iteration

In [19]:
# 1D array
a = np.array([1, 2, 3, 4, 5, 6])

for i in a:
  print(i)

# 2D array
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for j in b:
  print(j)

for k in b:
  for l in k:
    print(l)


c = np.array([[[1, 2, 3], [3, 4, 5]]])
for m in c:
  print(m)

for x in c:
  for y in x:
    for z in y:
      print(z)


1
2
3
4
5
6
[1 2 3 4]
[5 6 7 8]
1
2
3
4
5
6
7
8
[[1 2 3]
 [3 4 5]]
1
2
3
3
4
5


Iteration using nditer

In [22]:
c = np.array([[[1, 2, 3], [3, 4, 5]]])

for i in np.nditer(c):
# for i in np.nditer(c, flags=['buffered'], op_dtypes=["S"]): optional to convert data into string
  print(i)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')


Iteration using ndenumerate, by index number

In [27]:
c = np.array([[[1, 2, 3], [3, 4, 5]]])

for i in np.ndenumerate(c):
  print(i)

c = np.array([[[1, 2, 3], [3, 4, 5]]])

for i,d in np.ndenumerate(c):
  print(i,d)

((0, 0, 0), np.int64(1))
((0, 0, 1), np.int64(2))
((0, 0, 2), np.int64(3))
((0, 1, 0), np.int64(3))
((0, 1, 1), np.int64(4))
((0, 1, 2), np.int64(5))
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 3
(0, 1, 1) 4
(0, 1, 2) 5


Copy Vs View

In [30]:
# if we change the original data copied data will not be changed, but view will be changed

a = np.array([1, 2, 3, 4])
b = a.copy()
c = a.view()
a[1] = 7
print(f"a is: {a}")
print(f"copy is: {b}")
print(f"view is: {c}")

a is: [1 7 3 4]
copy is: [1 2 3 4]
view is: [1 7 3 4]


Join and Split array using (concatenate, stack, array_split)

Join Array using concatenate

In [45]:
# 1D array

a1 = np.array([1, 2, 3])
b1 = np.array([4, 5, 0])
c1 = np.concatenate((a1, b1))
print(c1)

# 2D array
a2 = np.array([[1, 2, 3], [4, 5, 6]])
b2 = np.array([[4, 5, 0], [7, 8, 9]])
#    axis is for axis numbers 0,1
c2 = np.concatenate((a2, b2), axis=1)
d2 = np.concatenate((a2, b2), axis=0)
print(c2)
print(d2)

[1 2 3 4 5 0]
[[1 2 3 4 5 0]
 [4 5 6 7 8 9]]
[[1 2 3]
 [4 5 6]
 [4 5 0]
 [7 8 9]]


Join Array using stack

In [58]:
a1 = np.array([1, 2, 3])
b1 = np.array([4, 5, 0])
# stack work according to axis 0, 1
c1 = np.stack((a1, b1), axis = 0)
c1 = np.hstack((a1, b1)) # merging data along row/ horizentally
c1 = np.vstack((a1, b1)) # merging data along column/ vertically
c1 = np.dstack((a1, b1)) # merging data along height/ dimentionally
print(c1)

[[[1 4]
  [2 5]
  [3 0]]]


Split array

In [69]:
# 1D array
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
#                      number of array of splitting
b = np.array_split(a, 3)
print(b)
print(b[0]) # printing 0 index array after splitting

# 2D array
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b1 = np.array_split(a1, 3)
c1 = np.array_split(a1, 3, axis = 1)
print(b1)
print(c1)


[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


Numpy array functions(Search, Sort, Search Sorted, Filter)

Search array

In [73]:
a = np.array([1, 4, 2, 3, 4, 5, 6, 7, 8, 4])
x = np.where(a == 4)
y = np.where(a%2 == 0)
print(x)
print(y)


(array([1, 4, 9]),)
(array([1, 2, 4, 6, 8, 9]),)


Search sorted array

In [78]:
# search where we can sort the value
a = np.array([1, 4, 2, 3, 4, 6, 7, 8, 4])
x = np.searchsorted(a, 5, side = "right") # side is optional
print(x)

b = np.array([1, 2, 3, 4, 5, 6, 7])
y = np.searchsorted(b, [0, 8, 9])
print(y)

5
[0 7 7]


Sort array

In [82]:
# 1D array
a = np.array([5, 9, 6, 3, 8, 2, 7, 1])
b = np.sort(a)
print(b)

c = np.array(["a", "s", "u", "z", "b"])
d = np.sort(c)
print(d)

# 2D array
a1 = np.array([[1, 9, 6, 3], [7, 3, 8, 1]])
b1 = np.sort(a1)
print(b1)

[1 2 3 5 6 7 8 9]
['a' 'b' 's' 'u' 'z']
[[1 3 6 9]
 [1 3 7 8]]


Filter array

In [83]:
# create a list mark true the value you want then add filter list in array
a = np.array([1, 2, 3, 4, 5])
f = [True, False, False, True, True]
b = a[f]
print(b)

[1 4 5]


Arithmetic functions (Shuffle, Unique, Resize, Flatten, Ravel)

Shuffle

In [84]:
 # Shuffle randomly
a = np.array([1, 2, 3, 4])
np.random.shuffle(a)
print(a)

[3 4 1 2]


Unique

In [86]:
# Only unique numbers, can also print index no
a = np.array([1, 1, 5, 8, 4, 9, 4, 5, 2, 3, 4])
#             for index no/ optional, counting of num by index no/optinal,
b = np.unique(a, return_index=True, return_counts=True)
print(b)

(array([1, 2, 3, 4, 5, 8, 9]), array([0, 8, 9, 4, 2, 3, 5]), array([2, 1, 1, 3, 2, 1, 1]))


Resize

In [87]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.resize(a, (2, 3)) # num of rows and columns
print(b )

[[1 2 3]
 [4 5 6]]


Flatten and ravel

In [94]:
# it convert 2D, 3D array into 1D array
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.flatten(order="F") # order is to change order "A", "C", "K", "F" bt default it's "C"
print(b)
c = np.ravel(a, order="K") # order is to change order "A", "C", "K", "F" bt default it's "C"
print(c)

[1 4 2 5 3 6]
[1 2 3 4 5 6]


Insert and delete


Insert

In [99]:
a = np.array([1, 2, 3, 4])
# np.insert(array name, position or index, value)
print(a)
b = np.insert(a, 2, 7)
print(b)

c = np.insert(a, (3, 4), 6)
print(c)

[1 2 3 4]
[1 2 7 3 4]
[1 2 3 6 4 6]


In [105]:
# 2D array

a = np.array([[1, 2, 3], [4, 5, 6]])
# b = np.insert(a, 2, 8, axis = 1)
b = np.insert(a, 2, [22, 23], axis = 1)
print(b)

[[ 1  2 22  3]
 [ 4  5 23  6]]


Append

In [116]:
a = np.array([1, 2, 3])
b = np.append(a, 9)
print(b)


a_1 = np.array([[1, 2, 3], [4, 5, 6]])
b_1 = np.append(a_1, [[22, 23, 25]], axis = 0)
print(b_1)

[1 2 3 9]
[[ 1  2  3]
 [ 4  5  6]
 [22 23 25]]


Delete

In [117]:
a = np.array([1, 2, 3])
b = np.delete(a, 1)
print(b)

[1 3]


Matrix

In [118]:
a = np.matrix([[1, 2, 3], [3, 4, 5]])
print(a)
print(type(a))

[[1 2 3]
 [3 4 5]]
<class 'numpy.matrix'>


Arithemtic operations in Matrix

In [119]:
# in 1D every operation is same like array
# In 2D and 3D array addition and subtraction same like array but multiplication is
a = np.matrix([[1, 2], [3, 4]])
b = np.matrix([[1, 2], [3, 4]])

c = a.dot(b)
print(c)


[[ 7 10]
 [15 22]]


Matrix funxtions (Transpose, Swapaxes, Inverse, Power, Determinate)

Transpose



In [121]:
a = np.matrix([[1, 2], [3, 4]])
b = a.transpose()
c = np.transpose(a)
print(b)
print(c)

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


Swapaxes

In [3]:
# to convert the axis
a = np.matrix([[1, 2], [3, 4]])
print(np.swapaxes(a, 0, 1))

[[1 3]
 [2 4]]


Inverse

In [4]:
a = np.matrix([[1, 2], [3, 4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


Power

In [7]:
# Three conditions
# power == 0 -> identity matrix
# power > 0 -> power(multiply)
# power < 0 -> inverse x power

a = np.matrix([[1, 2], [3, 4]])
print(np.linalg.matrix_power(a, 0))
print(np.linalg.matrix_power(a, -2))
print(np.linalg.matrix_power(a, 2))

[[1 0]
 [0 1]]
[[ 5.5  -2.5 ]
 [-3.75  1.75]]
[[ 7 10]
 [15 22]]


Determinent

In [9]:
# when two rows are same it will be zero
a = np.matrix([[1, 2, 5], [3, 4, 6], [7, 8, 9]])
print(np.linalg.det(a))

b = np.matrix([[1, 2], [3, 4]])
print(np.linalg.det(b))


-2.000000000000003
-2.0000000000000004


# NumPy Tutorial

This notebook explores fundamental concepts and operations in the NumPy library for numerical computing in Python.

## Array Creation and Properties

- Creating arrays from Python lists.
- Checking array type and dimensions (`ndim`).
- Creating arrays with a specified number of dimensions (`ndmin`).
- Creating arrays filled with zeros (`zeros`).
- Creating arrays filled with ones (`ones`).
- Creating empty arrays (`empty`).
- Creating arrays with a range of values (`arange`).
- Creating identity matrices (`eye`).
- Creating evenly spaced values within an interval (`linspace`).
- Creating arrays with random numbers (`random.rand`, `random.randn`, `random.ranf`, `random.randint`).

## Data Types

- Understanding different data types in NumPy arrays (`dtype`).
- Converting data types of arrays.

## Arithmetic Operations

- Performing element-wise arithmetic operations between arrays and scalars.
- Performing element-wise arithmetic operations between two arrays.
- Using NumPy's arithmetic functions (`add`, `subtract`, `multiply`, `divide`, `mod`, `power`, `reciprocal`).
- Performing arithmetic operations on 2D arrays.

## Arithmetic Functions

- Using common arithmetic functions like `max`, `min`, `argmin`, `argmax`, `sqrt`, `sin`, `cos`, `cumsum`.
- Applying arithmetic functions to 2D arrays along specific axes.

## Shape and Reshaping

- Checking the shape of an array (`shape`).
- Reshaping arrays into different dimensions (`reshape`).
- Reshaping to a 1D array (`reshape(-1)`).

## Broadcasting

- Understanding broadcasting rules and errors.

## Indexing and Slicing

- Accessing elements in 1D, 2D, and 3D arrays using indexing.
- Slicing arrays to extract subsets of elements.

## Iteration

- Iterating through array elements using standard Python loops.
- Iterating through arrays using `np.nditer`.
- Iterating through arrays with index using `np.ndenumerate`.

## Copy vs View

- Differentiating between copying and viewing arrays and how changes affect the original and new arrays.

## Join and Split

- Joining arrays using `concatenate`, `stack`, `hstack`, `vstack`, and `dstack`.
- Splitting arrays using `array_split`.

## Search, Sort, and Filter

- Searching for elements in an array using `where`.
- Searching for insertion points in a sorted array using `searchsorted`.
- Sorting arrays using `sort`.
- Filtering arrays based on a boolean mask.

## Other Functions

- Shuffling array elements randomly using `shuffle`.
- Finding unique elements in an array using `unique`.
- Resizing arrays using `resize`.
- Flattening arrays to 1D using `flatten` and `ravel`.

## Insert and Delete

- Inserting elements into an array using `insert`.
- Appending elements to an array using `append`.
- Deleting elements from an array using `delete`.

## Matrix Operations

- Creating NumPy matrices.
- Performing arithmetic operations on matrices (including dot product).
- Using matrix functions like `transpose`, `swapaxes`, `linalg.inv` (inverse), `linalg.matrix_power`, and `linalg.det` (determinant).